name: Run Telegram Bot

# Define when the workflow should run
on:
  schedule:
    # Cron schedule to run the workflow every 30 minutes (adjust as necessary)
    - cron: "*/30 * * * *"
  workflow_dispatch: # Allows manual triggering via GitHub UI

# Define the job that will run your bot
jobs:
  run-bot:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu as the environment

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.x
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt      # Install dependencies

      # Step 4: Run your bot script
      - name: Run the Telegram Bot
        env: # Define environment variables (securely stored in GitHub Secrets)
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          python main.py  # Replace 'your_bot_script.py' with the actual name of your bot script
